const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const page = fs.readFileSync(path.join(root, 'src/app/pages/SnsRecordsPage.tsx'), 'utf8');
const component = fs.readFileSync(path.join(root, 'src/app/components/SnsStoryCreator.tsx'), 'utf8');
const requestState = fs.readFileSync(path.join(root, 'src/app/utils/snsStoryRequestState.ts'), 'utf8');
const routes = fs.readFileSync(path.join(root, 'src/app/App.tsx'), 'utf8');
const sayu = fs.readFileSync(path.join(root, 'src/app/pages/SayuPage.tsx'), 'utf8');
const home = fs.readFileSync(path.join(root, 'src/app/pages/HomePageV2.tsx'), 'utf8');
const recordHub = fs.readFileSync(path.join(root, 'src/app/pages/RecordHubPage.tsx'), 'utf8');
const sayuModal = fs.readFileSync(path.join(root, 'src/app/components/SayuModal.tsx'), 'utf8');
const firestoreService = fs.readFileSync(path.join(root, 'src/app/services/firestoreService.ts'), 'utf8');
const snsStoryFunction = fs.readFileSync(path.resolve(root, '../functions/src/snsStory.ts'), 'utf8');

assert(page.includes("import { SnsStoryCreator }"), 'SnsRecordsPage must render the new SNS story creator');
assert(page.includes('<SnsStoryCreator'), 'autobio tab must mount SnsStoryCreator');
assert(!page.includes("toast.info('준비 중입니다')"), 'the old 준비 중입니다 toast must be removed');
assert(page.includes("return <SnsRecordsContent key={user?.uid || 'signed-out'} />"), 'uid keyed remount must remain');

assert(component.includes('activeSnsRecords(rawRecords)'), 'period candidates must be calculated after activeSnsRecords(rawRecords)');
assert(component.includes('serverReady'), 'server readiness must gate generation');
assert(component.includes('최신 서버 기록 확인 중입니다'), 'UI must explain disabled generation while server records are pending');
assert(component.includes('setExcludedIds(new Set())'), 'period changes must reset excluded selections');
assert(component.includes("setSourceFingerprint('')"), 'period/selection changes must reset fingerprint');
assert(component.includes('전체') && component.includes('포함') && component.includes('제외'), 'target counts must include total/included/excluded');
assert(component.includes('글만') && component.includes('사진만') && component.includes('글+사진'), 'target counts must include content type counts');
assert(component.includes('이 이야기에서 제외'), 'record checkboxes must be exclusion controls');
assert(component.includes('사진 내용은 분석하지 않습니다'), 'UI must disclose that photo content is not analyzed');
assert(component.includes('<textarea'), 'generated synopsis must be directly editable');
assert(component.includes('confirmedSynopsis: synopsis.trim()'), 'final generation must send the edited synopsis');
assert(component.includes('setSourceRecordIds(data.sourceRecordIds || [])'), 'synopsis source ids must be kept for final generation');
assert(component.includes('sourceRecordIds,'), 'final generation must send the server-returned source ids');
assert(component.includes('synopsisRequestRef') && component.includes('finalRequestRef'), 'duplicate clicks must reuse in-flight request state');
assert(component.includes('createSnsStoryRequestCoordinator'), 'late callable responses must be guarded by a request coordinator');
assert(component.includes('requestCoordinatorRef.current.isCurrent'), 'late callable responses must match the latest logical selection');
assert(component.includes('isCurrentSynopsisRequest()') && component.includes('isCurrentFinalRequest()'), 'late callable responses must not render after logout/user switch or input changes');
assert(component.includes("source === 'sns_story' && item.generationStatus === 'completed'"), 'SNS artwork list must only show completed sns_story records');
assert(component.includes("httpsCallable(functions, 'generateSnsStorySynopsis',"), 'frontend must call generateSnsStorySynopsis with explicit options');
assert(component.includes("timeout: SNS_STORY_SYNOPSIS_CALLABLE_TIMEOUT_MS"), 'synopsis callable timeout must exceed server timeout');
assert(component.includes("httpsCallable(functions, 'generateSnsStoryFinal',"), 'frontend must call generateSnsStoryFinal with explicit options');
assert(component.includes("timeout: SNS_STORY_FINAL_CALLABLE_TIMEOUT_MS"), 'final callable timeout must exceed server timeout');
assert(component.includes('getOrCreateDurableSnsStoryRequestTimestamp'), 'final retries must reuse durable request timestamps for the same logical input');
assert(component.includes('isSnsStoryAmbiguousCallableError'), 'network/timeout errors must be treated as ambiguous, retryable outcomes');
assert(component.includes('SNS 갈무리에서 보기'), 'completed SNS story saves must offer a Sayu navigation button');
assert(component.includes("filterFormat: SNS_GALMURI_LABEL"), 'completed SNS story navigation must target the SNS 갈무리 Sayu group');
assert(component.includes('aria-expanded={expanded}'), 'saved SNS artworks must expose accessible expand/collapse state');
assert(component.includes('전문 보기') && component.includes('접기'), 'saved SNS artworks must support full-text view and collapse');
assert(component.includes("const content = artwork.essay_sayu || artwork.content || '';"), 'saved artwork previews must prefer edited essay_sayu over original content and fall back to content');
assert(component.includes('const visibleContent = expanded || content.length <= 180'), 'saved artwork expand/collapse must still derive from the selected display content');
assert(component.includes("SNS 갈무리 · 저장된 작품"), 'saved artwork list must use the SNS 갈무리 naming');
assert(requestState.includes('buildSnsStoryFinalLogicalKey'), 'final idempotency key helper must be present');
assert(requestState.includes('logicalKeyHash') && !requestState.includes('RAW_SNS_BODY_SECRET'), 'durable operation storage must be hash-based');
assert(sayu.includes("function isCompletedSnsStoryRecord"), 'SayuPage must identify completed sns_story records explicitly');
assert(sayu.includes("record.source === 'sns_story' && record.generationStatus === 'completed'"), 'SNS 갈무리 records must be detected by source and completed status');
assert(sayu.includes('if (isCompletedSnsStoryRecord(record)) return false;'), 'SNS 갈무리 records must not be hidden as Gemini knowledge warehouse records');
assert(sayu.includes('label: SNS_GALMURI_LABEL'), 'completed SNS stories must be listed under the SNS 갈무리 assistant group');
assert(sayu.includes("onOpen: () => openFormatSayu(record.date, 'essay', SNS_GALMURI_LABEL, record.id)"), 'SNS 갈무리 entries must reuse essay detail rendering');
assert(sayu.includes("filterFormat === SNS_GALMURI_LABEL ? 'essay'"), 'SNS 갈무리 route state must map to essay detail fields');
assert(sayuModal.includes("data.source === 'sns_story' && data.generationStatus === 'completed'"), 'SNS 갈무리 completed artwork deletes must use a dedicated branch');
assert(sayuModal.includes('await deleteDoc(recordRef);'), 'SNS 갈무리 completed artwork deletes must remove the generated artwork record document');
assert(sayuModal.includes('await firestoreService.unpublishSharedRecord(currentUser.uid, docId);'), 'SNS 갈무리 completed artwork deletes must deactivate any public shared copy before deleting the source record');
assert(sayuModal.includes('onClose(true);') && sayuModal.includes('onRefresh?.();'), 'SNS 갈무리 deletes must refresh the caller after deletion');
const snsStoryDeleteBranchIndex = sayuModal.indexOf("data.source === 'sns_story' && data.generationStatus === 'completed'");
const snsStoryUnpublishIndex = sayuModal.indexOf('await firestoreService.unpublishSharedRecord(currentUser.uid, docId);', snsStoryDeleteBranchIndex);
const snsStoryDeleteDocIndex = sayuModal.indexOf('await deleteDoc(recordRef);', snsStoryDeleteBranchIndex);
const snsStoryDeleteReturnIndex = sayuModal.indexOf('return;', snsStoryDeleteBranchIndex);
const formatPhotoListIndex = sayuModal.indexOf('const listResult = await listAll(storageRef);');
assert(snsStoryDeleteBranchIndex > -1 && snsStoryDeleteReturnIndex > snsStoryDeleteBranchIndex, 'SNS 갈무리 delete branch must return before general essay cleanup');
assert(snsStoryUnpublishIndex > snsStoryDeleteBranchIndex && snsStoryDeleteDocIndex > snsStoryUnpublishIndex, 'SNS 갈무리 public shared copies must be unpublished before the source record is deleted');
assert(formatPhotoListIndex > snsStoryDeleteReturnIndex, 'SNS 갈무리 deletes must not run general format photo cleanup');
assert(!sayuModal.includes("'snsRecords'") && !sayuModal.includes('"snsRecords"'), 'SNS 갈무리 artwork deletes must not delete original SNS import records');
assert(firestoreService.includes('isActive: false'), 'shared record unpublish flow must deactivate public copies instead of leaving them visible');
assert(sayuModal.includes('fieldsToDelete') && sayuModal.includes("updateData['formats'] = arrayRemove(formatLabel)") && sayuModal.includes('await updateDoc(recordRef, updateData)'), 'normal essay format deletion must remain field-based');
const leaseFunctionIndex = snsStoryFunction.indexOf('async function leaseSnsStoryFinalOperation');
const completedRecoverIndex = snsStoryFunction.indexOf("if (existing.generationStatus === 'completed')", leaseFunctionIndex);
const reLeaseIndex = snsStoryFunction.indexOf("operationStatus: 'generating'", completedRecoverIndex);
assert(snsStoryFunction.indexOf('if (recordSnap.exists)', leaseFunctionIndex) < completedRecoverIndex, 'server must only recover completed SNS story operations when the target artwork record still exists');
assert(reLeaseIndex > completedRecoverIndex, 'server must allow the same payload operation to regenerate after the artwork record is deleted');
assert(home.includes("label: 'SNS 갈무리'"), 'home card must use SNS 갈무리 naming');
assert(recordHub.includes("label: 'SNS 갈무리'"), 'record hub card must use SNS 갈무리 naming');
assert(page.includes('SNS 갈무리 비서'), 'SNS records page title must use SNS 갈무리 비서 naming');
assert(!routes.includes('sns-story'), 'no new SNS story route should be added');

console.log('sns story creator policy tests passed');
