import { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router';
import { getFunctions, httpsCallable } from 'firebase/functions';
import { useLoading } from '../contexts/LoadingContext';
import { toast } from 'sonner';
import { ProphecyDiagram } from '../components/ProphecyDiagram';
import { PageHeaderActions } from '../components/PageHeaderActions';

// === 9개 항목 칩 옵션 ===
const ANALYSIS_MOTIVE_CHIPS = ['예상치 못한 만남', '오랜 꿈을 향한 첫 걸음', '위기에서 찾은 기회', '관계의 균열과 회복', '성공적인 기술 구현과 삶의 변화', '오랜 갈등의 해소'];
const ANALYSIS_THEME_CHIPS = ['두려움을 이기는 용기', '좌절을 딛고 새로운 삶 창조', '관계 속에서 발견하는 나', '포기하지 않는 자의 열매', '운명보다 강한 의지', '작은 것에서 찾는 삶의 의미'];
const ANALYSIS_PERSONALITY_CHIPS = ['신중하고 완벽주의 성향', '감성적이고 공감 능력이 뛰어남', '도전적이고 추진력이 강함', '따뜻하지만 우유부단한 면이 있음', '냉철하고 현실적인 판단력', '유머감각이 있고 분위기를 살림', '고집스럽지만 의리가 있음', '결정적인 순간에 강함'];
const ANALYSIS_GOAL_CHIPS = ['내가 시작한 일이 세상에 쓸모있게 남는 것', '경제적으로 자유로워지는 것', '나만의 작품을 완성하는 것', '내가 믿는 가치대로 사는 것', '나를 필요로 하는 곳에서 빛나는 것', '사랑하는 사람과 평온하게 사는 것'];
const ANALYSIS_SHACKLE_CHIPS = ['과거의 실패와 후회', '자기 자신에 대한 불신', '주변의 시선과 편견', '경제적 어려움', '건강의 한계', '포기하고 싶은 마음'];
const ANALYSIS_EVENT_CHIPS = ['예상치 못한 사고를 겪었다', '중요한 결정을 내려야 했다', '오랜 관계가 갑자기 변했다', '기회가 찾아왔지만 놓쳤다', '뜻밖의 도움을 받았다', '오랜 꿈에 도전했다'];
const ANALYSIS_DAILY_ACHIEVE_CHIPS = ['오랫동안 미뤄온 일을 드디어 시작했다', '가족과 함께 소소한 시간을 보냈다', '작은 목표 하나를 끝냈다', '누군가에게 먼저 연락했다', '오늘 하루를 기록으로 남겼다', '건강을 위해 한 걸음 내딛었다'];

// 칩 복수선택 토글 헬퍼
const ANALYSIS_CHIP_SEP = '、';
const toggleAnalysisChip = (currentValue: string, chipText: string): string => {
  const items = currentValue ? currentValue.split(ANALYSIS_CHIP_SEP).filter(Boolean) : [];
  if (items.includes(chipText)) {
    return items.filter(x => x !== chipText).join(ANALYSIS_CHIP_SEP);
  }
  return [...items, chipText].join(ANALYSIS_CHIP_SEP);
};
const isAnalysisChipActive = (currentValue: string, chipText: string): boolean => {
  if (!currentValue) return false;
  return currentValue.split(ANALYSIS_CHIP_SEP).filter(Boolean).includes(chipText);
};

export function NovelSynopsisPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { showLoading, hideLoading } = useLoading();
  const [synopsis, setSynopsis] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  const settings = location.state?.settings || {};
  const fromRecord = location.state?.fromRecord || false;
  const recordContent = location.state?.recordContent || '';
  const recordTitle = location.state?.recordTitle || '';
  const recordDate = location.state?.recordDate || '';
  const recordFormat = location.state?.recordFormat || '';
  const prophecyType = location.state?.prophecyType || '나의 미래';
  const timeOption = location.state?.timeOption || '3년 후';
  const question = location.state?.question || '';
  const prophecyGoalType = location.state?.prophecyGoalType || '';
  const prophecyGoal = location.state?.prophecyGoal || '';
  const prophecyWall = location.state?.prophecyWall || '';
  const navExtractedGoal = location.state?.extractedGoal || '';
  const navPersons = location.state?.persons || [];
  const navExtractedEvent = location.state?.extractedEvent || '';
  const navExtractedDailyAchieve = location.state?.extractedDailyAchieve || '';
  const navCurrentAge = location.state?.currentAge ?? null;
  const navBaseYear = location.state?.baseYear ?? null;
  const navFutureYear = location.state?.futureYear ?? null;
  const navFutureAge = location.state?.futureAge ?? null;
  const navProtagonistName = location.state?.protagonistName ?? null;

  // ── fromRecord=true 분기 전용 state ──
  const [analysis, setAnalysis] = useState({
    chars: location.state?.extractedChars || '',
    desire: location.state?.extractedGoal || location.state?.extractedDesire || '',
    shackle: location.state?.extractedShackle || '',
    events: location.state?.extractedEvent || location.state?.extractedEvents || '',
    relationship: location.state?.extractedRelationship || '',
    personality: location.state?.extractedPersonality || '',
    motive: location.state?.extractedMotive || '',
    theme: location.state?.extractedTheme || '',
    oneLiner: location.state?.extractedOneLiner || '',
    threeLiner: location.state?.extractedThreeLiner || '',
    dailyAchieve: location.state?.extractedDailyAchieve || '',
  });
  const [synopsisRound, setSynopsisRound] = useState<1 | 2 | 3>(1);
  const autoGeneratedRef = useRef(false);

  // ── fromRecord=false (자유 창작 모드) 기존 흐름 그대로 ──
  // flat settings → Functions가 기대하는 문자열 직렬화
  const buildFreeModePayload = (type: 'synopsis' | 'story') => {
    const join = (arr: string[] | undefined) => (arr || []).filter(Boolean).join(', ');
    return {
      fromRecord: false,
      motive: settings.motive,
      motiveCustom: settings.motiveCustom,
      timeOption: settings.timeOption || '3년 후',
      chars: settings.chars || [],
      events: settings.events || [],
      birth: [
        settings.birthGender && `성별: ${settings.birthGender}${settings.birthGenderMemo ? `(${settings.birthGenderMemo})` : ''}`,
        settings.birthSpoon && `경제: ${settings.birthSpoon}${settings.birthSpoonMemo ? `(${settings.birthSpoonMemo})` : ''}`,
        settings.birthLooks && `외모: ${settings.birthLooks}${settings.birthLooksMemo ? `(${settings.birthLooksMemo})` : ''}`,
        (settings.birthEras?.length) && `시대: ${join(settings.birthEras)}${settings.birthEraMemo ? `(${settings.birthEraMemo})` : ''}`,
        (settings.birthRegions?.length) && `지역: ${join(settings.birthRegions)}${settings.birthRegionMemo ? `(${settings.birthRegionMemo})` : ''}`,
        (settings.birthFamilies?.length) && `가정: ${join(settings.birthFamilies)}${settings.birthFamilyMemo ? `(${settings.birthFamilyMemo})` : ''}`,
        (settings.birthSocials?.length) && `사회: ${join(settings.birthSocials)}${settings.birthSocialMemo ? `(${settings.birthSocialMemo})` : ''}`,
      ].filter(Boolean).join(' | '),
      desire: [
        (settings.desireItems?.length) && `핵심욕망: ${join(settings.desireItems)}`,
        settings.desireMemo,
        settings.desireIntensity && `욕망강도: ${settings.desireIntensity}/7`,
        (settings.desireLimits?.length) && `현실적 한계: ${join(settings.desireLimits)}`,
        settings.desireLimitMemo,
      ].filter(Boolean).join(' | '),
      shackle: [
        (settings.shackleItems?.length) && `족쇄: ${join(settings.shackleItems)}`,
        settings.shackleMemo,
        (settings.shackleYearns?.length) && `갈구함 표현: ${join(settings.shackleYearns)}`,
        settings.shackleYarnMemo,
      ].filter(Boolean).join(' | '),
      luck: [
        (settings.luckStages?.filter(Boolean).length) && `전환점: ${(settings.luckStages || []).filter(Boolean).join(', ')}`,
        settings.luckMemo,
      ].filter(Boolean).join(' | '),
      unluck: [
        (settings.unluckItems?.length) && join(settings.unluckItems),
        settings.unluckCustom,
      ].filter(Boolean).join(', '),
      narrative: [
        (settings.narrativeWriters?.length) && `작가스타일: ${join(settings.narrativeWriters)}`,
        settings.narrativeWriterMemo,
        (settings.narrativeConflicts?.length) && `갈등구조: ${join(settings.narrativeConflicts)}`,
        settings.narrativeConflictMemo,
        (settings.narrativeDevices?.length) && `서사장치: ${join(settings.narrativeDevices)}`,
      ].filter(Boolean).join(' | '),
      type,
    };
  };

  const handleGenerateSynopsisLegacy = async () => {
    setIsGenerating(true);
    showLoading('🔮 AI가 당신의 미래를 전망하고 있습니다...');
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');
      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const result: any = await fn(buildFreeModePayload('synopsis'));
      setSynopsis(result.data.text);
      toast.success('시놉시스가 생성되었습니다!');
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  const handleGenerateStoryLegacy = async () => {
    setIsGenerating(true);
    showLoading('🔮 AI가 당신만의 이야기를 쓰고 있습니다...\n좋은 이야기는 시간이 걸립니다. 잠시만 기다려주세요.');
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');
      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const result: any = await fn(buildFreeModePayload('story'));
      navigate('/novel-story', {
        state: {
          story: result.data.text,
          settings,
          fromRecord,
          timeOption: settings.timeOption || '3년 후',
        }
      });
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  // ── fromRecord=true 분기 전용 함수 ──
  const goalTypeToKorean: Record<string, string> = {
    me: '나의 미래',
    child: '자식의 미래',
    past: '과거를 바꿨다면',
  };

  const buildPayload = (currentAnalysis: typeof analysis, payloadType: 'synopsis' | 'story') => ({
    fromRecord: true,
    recordContent, recordTitle, recordDate, recordFormat,
    prophecyType: goalTypeToKorean[prophecyGoalType as string] || prophecyType,
    timeOption,
    question: prophecyWall || question,
    prophecyGoalType, prophecyGoal, prophecyWall,
    extractedChars: currentAnalysis.chars,
    extractedShackle: currentAnalysis.shackle,
    extractedEvents: currentAnalysis.events,
    extractedRelationship: currentAnalysis.relationship,
    extractedPersonality: currentAnalysis.personality,
    extractedMotive: currentAnalysis.motive,
    extractedTheme: currentAnalysis.theme,
    extractedThreeLiner: currentAnalysis.threeLiner,
    extractedGoal: currentAnalysis.desire || navExtractedGoal,
    persons: navPersons,
    extractedEvent: currentAnalysis.events || navExtractedEvent,
    extractedDailyAchieve: currentAnalysis.dailyAchieve || navExtractedDailyAchieve,
    currentAge: navCurrentAge,
    baseYear: navBaseYear,
    futureYear: navFutureYear,
    futureAge: navFutureAge,
    protagonistName: navProtagonistName,
    type: payloadType,
  });

  const handleGenerateSynopsis = async (regenerate: boolean = false) => {
    setIsGenerating(true);
    showLoading(regenerate ? '🔮 사용자 수정안을 반영해 다시 분석 중...' : '🔮 AI가 당신의 미래를 전망하고 있습니다...');
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');

      let nextAnalysis = analysis;
      let nextRound: 1 | 2 | 3 = synopsisRound;

      if (regenerate) {
        nextRound = (synopsisRound + 1) as 2 | 3;
        const analyzeFn = httpsCallable(functions, 'analyzeRecordForProphecy');
        const analyzeRes: any = await analyzeFn({
          content: recordContent,
          userAnalysis: analysis,
          round: nextRound,
        });
        const d = analyzeRes.data;
        nextAnalysis = {
          chars: d.chars || '',
          desire: d.desire || '',
          shackle: d.shackle || '',
          events: d.events || '',
          relationship: d.relationship || '',
          personality: d.personality || '',
          motive: d.motive || '',
          theme: d.theme || '',
          oneLiner: d.oneLiner || '',
          threeLiner: d.threeLiner || '',
          dailyAchieve: analysis.dailyAchieve || '',
        };
        setAnalysis(nextAnalysis);
        setSynopsisRound(nextRound);
      }

      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const result: any = await fn(buildPayload(nextAnalysis, 'synopsis'));
      setSynopsis(result.data.text);
      if (regenerate) toast.success(`${nextRound}차 시놉시스가 생성되었습니다!`);
      else toast.success('시놉시스가 생성되었습니다!');
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  const handleGenerateStory = async () => {
    setIsGenerating(true);
    const loadingMsg = navProtagonistName
      ? `🔮 ${navProtagonistName}의 ${timeOption} 이야기를 쓰고 있습니다...\n좋은 이야기는 시간이 걸립니다. 잠시만 기다려주세요.`
      : '🔮 AI가 당신의 이야기를 쓰고 있습니다...\n좋은 이야기는 시간이 걸립니다. 잠시만 기다려주세요.';
    showLoading(loadingMsg);
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');
      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const result: any = await fn(buildPayload(analysis, 'story'));
      navigate('/novel-story', {
        state: {
          story: result.data.text,
          settings,
          fromRecord,
          recordDate,
          recordTitle,
          recordFormat,
          protagonistName: navProtagonistName,
          timeOption,
        }
      });
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (fromRecord && !autoGeneratedRef.current && !synopsis && !isGenerating) {
      autoGeneratedRef.current = true;
      handleGenerateSynopsis(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const renderAnalysisAsText = (a: typeof analysis): string => {
    return `【사건 모티브】\n${a.motive || '(미입력)'}\n
【주제·기획의도】\n${a.theme || '(미입력)'}\n
【세 줄 스토리】\n${a.threeLiner || '(미입력)'}\n
【등장인물 & 관계】\n${a.chars || '(미입력)'}${a.relationship ? ' / ' + a.relationship : ''}\n
【등장인물별 성격】\n${a.personality || '(미입력)'}\n
【초목표】\n${a.desire || '(미입력)'}\n
【주인공이 극복할 것】\n${a.shackle || '(미입력)'}\n
【나에게 일어난 사건】\n${a.events || '(미입력)'}\n
【일상에서 이룬 일】\n${a.dailyAchieve || '(미입력)'}`.trim();
  };

  const navPersonsList = Array.isArray(navPersons) ? navPersons : [];
  const personSummaryFromNav = navPersonsList
    .map((p: any) => [p?.name, p?.relation].filter(Boolean).join(' - '))
    .filter(Boolean)
    .join(', ');
  const charsSummary = personSummaryFromNav || [analysis.chars, analysis.relationship].filter(Boolean).join(' / ');
  const currentAgeText = navCurrentAge !== null && navCurrentAge !== undefined && navCurrentAge !== '' ? `${navCurrentAge}세` : '';
  const futureAgeText = navFutureAge !== null && navFutureAge !== undefined && navFutureAge !== '' ? `${navFutureAge}세` : '';
  const ageSummary = currentAgeText && futureAgeText
    ? `${currentAgeText} → ${futureAgeText}`
    : currentAgeText || futureAgeText;
  const protagonistDetail = [ageSummary, (navProtagonistName || ageSummary) && timeOption ? `(${timeOption})` : ''].filter(Boolean).join(' ');
  const protagonistSummary = navProtagonistName || ageSummary
    ? [navProtagonistName, protagonistDetail].filter(Boolean).join(' · ')
    : '';
  const summaryRows = [
    { label: '🧑 주인공', value: protagonistSummary },
    { label: '🎯 초목표', value: analysis.desire || navExtractedGoal },
    { label: '⛓ 극복할 것', value: analysis.shackle },
    { label: '👥 등장인물', value: charsSummary },
    { label: '⚡ 사건 모티브', value: analysis.motive },
    { label: '📌 주요 사건', value: analysis.events || navExtractedEvent },
    { label: '🎯 주제', value: analysis.theme },
  ].filter(row => String(row.value || '').trim());

  // 자유 창작 모드 — 설정 요약 행
  const freeSettingRows = [
    { label: '⏰ 시간', value: settings.timeOption },
    { label: '🔥 욕망', value: [(settings.desireItems || []).join(', '), settings.desireMemo].filter(Boolean).join(' / ') },
    { label: '⛓ 족쇄', value: [(settings.shackleItems || []).join(', '), settings.shackleMemo].filter(Boolean).join(' / ') },
    { label: '⚡ 핵심 사건', value: (settings.events || []).filter((e: any) => e.isCore).map((e: any) => e.title).join(', ') || (settings.events || []).map((e: any) => e.title).join(', ') },
    { label: '👥 시동자', value: (settings.chars || []).find((c: any) => c.role === '시동자')?.name },
    { label: '📖 서사 스타일', value: [(settings.narrativeWriters || []).join(', '), (settings.narrativeConflicts || []).join(', ')].filter(Boolean).join(' | ') },
  ].filter(row => String(row.value || '').trim());

  // ─────────────────────────────────────
  // RENDER — 자유 창작 모드
  // ─────────────────────────────────────
  if (!fromRecord) {
    return (
      <div style={{
        maxWidth: 640, margin: '0 auto', padding: '24px 16px',
        minHeight: 'calc(100vh - 56px - 80px)',
        backgroundColor: '#FAF9F6',
      }}>
        <PageHeaderActions />
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 22 }}>🔮</span>
            <h1 style={{ fontSize: 18, fontWeight: 700, color: '#1A3C6E', margin: 0 }}>HARU미래전망</h1>
          </div>
        </div>

        {/* 설정 요약 카드 */}
        {freeSettingRows.length > 0 && (
          <div style={{
            background: '#fff', border: '0.5px solid #e5e7eb',
            borderRadius: 12, padding: '14px 16px', marginBottom: 16,
          }}>
            <p style={{ fontSize: 12, fontWeight: 700, color: '#1A3C6E', margin: '0 0 10px' }}>📋 설정 요약</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {freeSettingRows.map((row, idx) => (
                <div key={idx} style={{ display: 'flex', gap: 8, fontSize: 12 }}>
                  <span style={{ color: '#6B7280', flexShrink: 0, width: 80 }}>{row.label}</span>
                  <span style={{ color: '#1f2937', lineHeight: 1.5 }}>{row.value}</span>
                </div>
              ))}
            </div>
            <button
              onClick={() => navigate('/novel-studio')}
              style={{
                marginTop: 10, padding: '5px 12px', fontSize: 11,
                borderRadius: 8, border: '1px solid #d1d5db',
                background: '#fff', color: '#6B7280', cursor: 'pointer',
              }}
            >✏️ 설정 수정</button>
          </div>
        )}

        {!synopsis && (
          <div style={{
            background: '#EEF2FF', border: '1px solid #C7D2FE',
            borderRadius: 14, padding: '24px', marginBottom: 24, textAlign: 'center',
          }}>
            <div style={{ fontSize: 40, marginBottom: 10 }}>🔮</div>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: '#1A3C6E', marginBottom: 8 }}>
              {settings.timeOption ? `${settings.timeOption} 후의 이야기를 전망합니다` : 'AI가 당신의 미래를 전망합니다'}
            </h2>
            <p style={{ fontSize: 12, color: '#6B7280', lineHeight: 1.8, margin: 0 }}>
              설정하신 내용을 바탕으로<br />
              Gemini AI가 당신만의 미래 서사를 생성합니다.<br /><br />
              <strong>"사주는 태어난 날을 봅니다.<br />
              HARU미래전망은 당신이 살아온 날을 봅니다."</strong>
            </p>
          </div>
        )}

        {synopsis && (
          <div style={{
            background: '#fff', border: '1.5px solid #C7D2FE',
            borderRadius: 14, padding: '20px', marginBottom: 20,
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12 }}>
              <span style={{ fontSize: 16 }}>🔮</span>
              <h2 style={{ fontSize: 15, fontWeight: 700, color: '#1A3C6E', margin: 0 }}>
                당신의 미래전망 시놉시스
              </h2>
            </div>
            <p style={{
              fontSize: 14, color: '#374151', lineHeight: 1.9,
              whiteSpace: 'pre-wrap', margin: 0,
            }}>{synopsis}</p>
          </div>
        )}

        {!synopsis ? (
          <button
            onClick={handleGenerateSynopsisLegacy}
            disabled={isGenerating}
            style={{
              width: '100%', padding: '16px', borderRadius: 12, border: 'none',
              background: isGenerating ? '#9ca3af' : '#1A3C6E',
              color: '#fff', fontSize: 15, fontWeight: 700,
              cursor: isGenerating ? 'not-allowed' : 'pointer', marginBottom: 12,
            }}
          >🔮 시놉시스 생성하기</button>
        ) : (
          <>
            <button
              onClick={() => navigate('/novel-studio')}
              style={{
                width: '100%', padding: '14px', borderRadius: 12,
                border: '2px solid #1A3C6E', background: '#fff', color: '#1A3C6E',
                fontSize: 14, fontWeight: 600, cursor: 'pointer', marginBottom: 10,
              }}
            >✏️ 서사 수정하기</button>

            <button
              onClick={handleGenerateSynopsisLegacy}
              disabled={isGenerating}
              style={{
                width: '100%', padding: '14px', borderRadius: 12,
                border: '1.5px solid #d1d5db', background: '#f9fafb', color: '#6B7280',
                fontSize: 13, fontWeight: 500,
                cursor: isGenerating ? 'not-allowed' : 'pointer', marginBottom: 10,
              }}
            >🔄 시놉시스 다시 생성</button>

            <button
              onClick={handleGenerateStoryLegacy}
              disabled={isGenerating}
              style={{
                width: '100%', padding: '16px', borderRadius: 12, border: 'none',
                background: isGenerating ? '#9ca3af' : '#10b981',
                color: '#fff', fontSize: 15, fontWeight: 700,
                cursor: isGenerating ? 'not-allowed' : 'pointer', marginBottom: 10,
              }}
            >📖 이야기 생성하기 (최종)</button>

            <button
              onClick={() => window.print()}
              style={{
                width: '100%', padding: '12px', borderRadius: 12,
                border: '1.5px solid #d1d5db', background: '#fff', color: '#6B7280',
                fontSize: 13, fontWeight: 500, cursor: 'pointer',
              }}
            >📄 PDF로 저장</button>
          </>
        )}
      </div>
    );
  }

  // ─────────────────────────────────────
  // RENDER — 기록 기반 모드 (구조 분석 + 3차 재생성)
  // ─────────────────────────────────────
  return (
    <div style={{
      maxWidth: 1100, margin: '0 auto', padding: '20px 16px',
      minHeight: 'calc(100vh - 56px - 80px)',
      backgroundColor: '#FAF9F6',
    }}>
      <PageHeaderActions />
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 22 }}>🔮</span>
          <h1 style={{ fontSize: 18, fontWeight: 700, color: '#1A3C6E', margin: 0 }}>
            HARU미래전망 — {synopsisRound}차 시놉시스
          </h1>
        </div>
      </div>

      <div style={{
        background: '#FFFBF0', border: '0.5px solid #F9CB42',
        borderRadius: 10, padding: '10px 12px', marginBottom: 16,
        fontSize: 12, color: '#633806', lineHeight: 1.7,
      }}>
        💡 왼쪽은 이야기 설정 요약, 오른쪽은 시놉시스 미리보기입니다.
        설정을 바꾸려면 요약 카드의 버튼으로 돌아가세요. (현재 {synopsisRound}차)
      </div>

      <ProphecyDiagram analysis={{
        chars: analysis.chars,
        relationship: analysis.relationship,
        desire: analysis.desire,
        shackle: analysis.shackle,
        events: analysis.events,
        theme: analysis.theme,
      }} />

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
        gap: 16,
        marginTop: 16,
      }} className="haru-split">
        <div style={{ background: '#fff', borderRadius: 14, padding: 16, border: '0.5px solid #e5e7eb' }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: '#1A3C6E', marginTop: 0, marginBottom: 14 }}>
            📋 이야기 설정 요약
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {summaryRows.map((row, idx) => (
              <div key={idx} style={{ borderBottom: idx < summaryRows.length - 1 ? '0.5px solid #f3f4f6' : 'none', paddingBottom: 10 }}>
                <p style={{ fontSize: 11, fontWeight: 700, color: '#1A3C6E', margin: '0 0 4px' }}>{row.label}</p>
                <p style={{
                  fontSize: 13, color: '#374151', lineHeight: 1.7,
                  whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0,
                }}>
                  {row.value}
                </p>
              </div>
            ))}
          </div>
          <button
            onClick={() => navigate(-1)}
            style={{
              marginTop: 16, padding: '8px 12px', borderRadius: 10,
              border: '1px solid #d1d5db', background: '#fff',
              color: '#1A3C6E', fontSize: 12, fontWeight: 600, cursor: 'pointer',
            }}
          >
            ← 설정으로 돌아가기
          </button>
          <p style={{ fontSize: 11, color: '#9ca3af', lineHeight: 1.7, margin: '12px 0 0' }}>
            설정을 바꾸고 싶으면 위 버튼으로 돌아가세요.<br />
            시놉시스를 확인한 후 최종 이야기를 생성하세요.
          </p>
        </div>

        <div style={{ background: '#fff', borderRadius: 14, padding: 20, border: '1.5px solid #C7D2FE' }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: '#1A3C6E', marginTop: 0, marginBottom: 14 }}>
            🔮 {synopsisRound}차 시놉시스 미리보기
          </h3>
          {!synopsis ? (
            <div style={{
              background: '#EEF2FF', border: '1px solid #C7D2FE',
              borderRadius: 12, padding: '24px 18px', textAlign: 'center',
            }}>
              <p style={{ fontSize: 14, color: '#1A3C6E', fontWeight: 700, lineHeight: 1.8, margin: 0 }}>
                🔮 AI가 설정 내용을 바탕으로 당신의 미래 이야기를 쓰고 있습니다.
              </p>
              <p style={{ fontSize: 12, color: '#374151', lineHeight: 1.8, margin: '14px 0' }}>
                "사주는 태어난 날을 봅니다.<br />
                HARU미래전망은 당신이 살아온 날을 봅니다."
              </p>
              <p style={{ fontSize: 12, color: '#6B7280', margin: 0 }}>
                잠시만 기다려주세요.
              </p>
            </div>
          ) : (
            <>
              <pre style={{
                fontSize: 13, color: '#374151', lineHeight: 1.9,
                whiteSpace: 'pre-wrap', wordBreak: 'break-word',
                margin: 0, fontFamily: 'inherit', maxHeight: 600, overflowY: 'auto',
              }}>
                {renderAnalysisAsText(analysis)}
              </pre>

              <div style={{ marginTop: 20, paddingTop: 14, borderTop: '0.5px dashed #d1d5db' }}>
                <p style={{ fontSize: 11, color: '#9ca3af', marginBottom: 6 }}>
                  🤖 AI가 생성한 시놉시스 본문
                </p>
                <p style={{
                  fontSize: 13, color: '#374151', lineHeight: 1.9,
                  whiteSpace: 'pre-wrap', margin: 0,
                }}>{synopsis}</p>
              </div>
            </>
          )}
        </div>
      </div>

      <div style={{ marginTop: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
        {synopsisRound < 3 && (
          <button
            onClick={() => handleGenerateSynopsis(true)}
            disabled={isGenerating}
            style={{
              width: '100%', padding: '14px', borderRadius: 12,
              border: '1.5px solid #1A3C6E', background: '#fff', color: '#1A3C6E',
              fontSize: 14, fontWeight: 600,
              cursor: isGenerating ? 'not-allowed' : 'pointer',
            }}
          >
            🔄 {synopsisRound + 1}차 시놉시스 생성 {synopsisRound === 2 ? '(마지막!)' : ''}
          </button>
        )}

        {synopsisRound >= 3 && (
          <div style={{
            background: '#F0FDF4', border: '0.5px solid #86EFAC',
            borderRadius: 10, padding: '10px 12px',
            fontSize: 12, color: '#15803D', textAlign: 'center',
          }}>
            ✅ 3차 시놉시스까지 완료되었습니다.<br />
            마음에 드는 시놉시스를 고른 후 이야기를 생성하세요.
          </div>
        )}

        <button
          onClick={handleGenerateStory}
          disabled={isGenerating}
          style={{
            width: '100%', padding: '16px', borderRadius: 12, border: 'none',
            background: isGenerating ? '#9ca3af' : '#10b981',
            color: '#fff', fontSize: 15, fontWeight: 700,
            cursor: isGenerating ? 'not-allowed' : 'pointer',
          }}
        >📖 최종 확정 → 이야기 생성하기</button>

        <button
          onClick={() => window.print()}
          style={{
            width: '100%', padding: '12px', borderRadius: 12,
            border: '1.5px solid #d1d5db', background: '#fff', color: '#6B7280',
            fontSize: 13, fontWeight: 500, cursor: 'pointer',
          }}
        >📄 시놉시스 PDF로 저장</button>
      </div>

      <style>{`
        @media (max-width: 768px) {
          .haru-split {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </div>
  );
}
