import { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router';
import { getFunctions, httpsCallable } from 'firebase/functions';
import { useLoading } from '../contexts/LoadingContext';
import { toast } from 'sonner';
import { ProphecyDiagram } from '../components/ProphecyDiagram';

export function NovelSynopsisPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { showLoading, hideLoading } = useLoading();
  const [synopsis, setSynopsis] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  const settings = location.state?.settings || {};
  const fromRecord = location.state?.fromRecord || false;
  const recordContent = location.state?.recordContent || '';
  const recordTitle = location.state?.recordTitle || '';
  const recordDate = location.state?.recordDate || '';
  const recordFormat = location.state?.recordFormat || '';
  const prophecyType = location.state?.prophecyType || '나의 미래';
  const timeOption = location.state?.timeOption || '3년 후';
  const question = location.state?.question || '';
  const prophecyGoalType = location.state?.prophecyGoalType || '';
  const prophecyGoal = location.state?.prophecyGoal || '';
  const prophecyWall = location.state?.prophecyWall || '';
  const navExtractedGoal = location.state?.extractedGoal || '';
  const navPersons = location.state?.persons || [];
  const navExtractedEvent = location.state?.extractedEvent || '';
  const navExtractedDailyAchieve = location.state?.extractedDailyAchieve || '';

  // ── fromRecord=true 분기 전용 state ──
  const [analysis, setAnalysis] = useState({
    chars: location.state?.extractedChars || '',
    desire: location.state?.extractedDesire || '',
    shackle: location.state?.extractedShackle || '',
    events: location.state?.extractedEvents || '',
    relationship: location.state?.extractedRelationship || '',
    personality: location.state?.extractedPersonality || '',
    motive: location.state?.extractedMotive || '',
    theme: location.state?.extractedTheme || '',
    oneLiner: location.state?.extractedOneLiner || '',
    threeLiner: location.state?.extractedThreeLiner || '',
  });
  const [synopsisRound, setSynopsisRound] = useState<1 | 2 | 3>(1);
  const autoGeneratedRef = useRef(false);

  // ── fromRecord=false (자유 창작 모드) 기존 흐름 그대로 ──
  const handleGenerateSynopsisLegacy = async () => {
    setIsGenerating(true);
    showLoading('🔮 AI가 당신의 미래를 예언하고 있습니다...');
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');
      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const payload = { ...settings, type: 'synopsis' };
      const result: any = await fn(payload);
      setSynopsis(result.data.text);
      toast.success('시놉시스가 생성되었습니다!');
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  const handleGenerateStoryLegacy = async () => {
    setIsGenerating(true);
    showLoading('🔮 AI가 당신의 이야기를 쓰고 있습니다... 잠시만 기다려주세요.');
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');
      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const payload = { ...settings, type: 'story' };
      const result: any = await fn(payload);
      navigate('/novel-story', { state: { story: result.data.text, settings, fromRecord } });
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  // ── fromRecord=true 분기 전용 함수 ──
  const goalTypeToKorean: Record<string, string> = {
    me: '나의 미래',
    child: '자식의 미래',
    past: '과거를 바꿨다면',
  };

  const buildPayload = (currentAnalysis: typeof analysis, payloadType: 'synopsis' | 'story') => ({
    fromRecord: true,
    recordContent, recordTitle, recordDate, recordFormat,
    prophecyType: goalTypeToKorean[prophecyGoalType as string] || prophecyType,
    timeOption,
    question: prophecyWall || question,
    prophecyGoalType, prophecyGoal, prophecyWall,
    extractedChars: currentAnalysis.chars,
    extractedShackle: currentAnalysis.shackle,
    extractedEvents: currentAnalysis.events,
    extractedRelationship: currentAnalysis.relationship,
    extractedPersonality: currentAnalysis.personality,
    extractedMotive: currentAnalysis.motive,
    extractedTheme: currentAnalysis.theme,
    extractedThreeLiner: currentAnalysis.threeLiner,
    extractedGoal: navExtractedGoal || currentAnalysis.desire,
    persons: navPersons,
    extractedEvent: navExtractedEvent,
    extractedDailyAchieve: navExtractedDailyAchieve,
    type: payloadType,
  });

  const handleGenerateSynopsis = async (regenerate: boolean = false) => {
    setIsGenerating(true);
    showLoading(regenerate ? '🔮 사용자 수정안을 반영해 다시 분석 중...' : '🔮 AI가 당신의 미래를 예언하고 있습니다...');
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');

      let nextAnalysis = analysis;
      let nextRound: 1 | 2 | 3 = synopsisRound;

      if (regenerate) {
        nextRound = (synopsisRound + 1) as 2 | 3;
        const analyzeFn = httpsCallable(functions, 'analyzeRecordForProphecy');
        const analyzeRes: any = await analyzeFn({
          content: recordContent,
          userAnalysis: analysis,
          round: nextRound,
        });
        const d = analyzeRes.data;
        nextAnalysis = {
          chars: d.chars || '',
          desire: d.desire || '',
          shackle: d.shackle || '',
          events: d.events || '',
          relationship: d.relationship || '',
          personality: d.personality || '',
          motive: d.motive || '',
          theme: d.theme || '',
          oneLiner: d.oneLiner || '',
          threeLiner: d.threeLiner || '',
        };
        setAnalysis(nextAnalysis);
        setSynopsisRound(nextRound);
      }

      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const result: any = await fn(buildPayload(nextAnalysis, 'synopsis'));
      setSynopsis(result.data.text);
      if (regenerate) toast.success(`${nextRound}차 시놉시스가 생성되었습니다!`);
      else toast.success('시놉시스가 생성되었습니다!');
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  const handleGenerateStory = async () => {
    setIsGenerating(true);
    showLoading('🔮 AI가 당신의 이야기를 쓰고 있습니다... 잠시만 기다려주세요.');
    try {
      const functions = getFunctions(undefined, 'asia-northeast3');
      const fn = httpsCallable(functions, 'generateHaruProphecy');
      const result: any = await fn(buildPayload(analysis, 'story'));
      navigate('/novel-story', { state: { story: result.data.text, settings, fromRecord } });
    } catch (error: any) {
      const msg = error?.message || '생성에 실패했습니다. 다시 시도해주세요.';
      toast.error(msg);
    } finally {
      hideLoading();
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (fromRecord && !autoGeneratedRef.current && !synopsis && !isGenerating) {
      autoGeneratedRef.current = true;
      handleGenerateSynopsis(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const renderAnalysisAsText = (a: typeof analysis): string => {
    return `【등장인물】\n${a.chars || '(미입력)'}\n
【인간관계】\n${a.relationship || '(미입력)'}\n
【인물 성격】\n${a.personality || '(미입력)'}\n
【추구하는 것】\n${a.desire || '(미입력)'}\n
【극복할 것】\n${a.shackle || '(미입력)'}\n
【주요 사건】\n${a.events || '(미입력)'}\n
【사건 모티브】\n${a.motive || '(미입력)'}\n
【주제·기획의도】\n${a.theme || '(미입력)'}\n
【한 줄 스토리】\n${a.oneLiner || '(미입력)'}\n
【세 줄 스토리】\n${a.threeLiner || '(미입력)'}`.trim();
  };

  // ─────────────────────────────────────
  // RENDER — 자유 창작 모드 (기존 UI 그대로)
  // ─────────────────────────────────────
  if (!fromRecord) {
    return (
      <div style={{
        maxWidth: 640, margin: '0 auto', padding: '24px 16px',
        minHeight: 'calc(100vh - 56px - 80px)',
        backgroundColor: '#FAF9F6',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 22 }}>🔮</span>
            <h1 style={{ fontSize: 18, fontWeight: 700, color: '#1A3C6E', margin: 0 }}>HARU예언</h1>
          </div>
          <button
            onClick={() => navigate('/novel-studio')}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              fontSize: 13, color: '#6B7280', padding: '6px 10px', borderRadius: 8,
            }}
          >← 설정으로</button>
        </div>

        {!synopsis && (
          <div style={{
            background: '#EEF2FF', border: '1px solid #C7D2FE',
            borderRadius: 14, padding: '24px', marginBottom: 24, textAlign: 'center',
          }}>
            <div style={{ fontSize: 40, marginBottom: 10 }}>🔮</div>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: '#1A3C6E', marginBottom: 8 }}>
              AI가 당신의 미래를 예언합니다
            </h2>
            <p style={{ fontSize: 12, color: '#6B7280', lineHeight: 1.8, margin: 0 }}>
              설정하신 내용을 바탕으로<br />
              Gemini AI가 당신만의 미래 서사를 생성합니다.<br /><br />
              <strong>"사주는 태어난 날을 봅니다.<br />
              HARU예언은 당신이 살아온 날을 봅니다."</strong>
            </p>
          </div>
        )}

        {synopsis && (
          <div style={{
            background: '#fff', border: '1.5px solid #C7D2FE',
            borderRadius: 14, padding: '20px', marginBottom: 20,
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12 }}>
              <span style={{ fontSize: 16 }}>🔮</span>
              <h2 style={{ fontSize: 15, fontWeight: 700, color: '#1A3C6E', margin: 0 }}>
                당신의 예언 시놉시스
              </h2>
            </div>
            <p style={{
              fontSize: 14, color: '#374151', lineHeight: 1.9,
              whiteSpace: 'pre-wrap', margin: 0,
            }}>{synopsis}</p>
          </div>
        )}

        {!synopsis ? (
          <button
            onClick={handleGenerateSynopsisLegacy}
            disabled={isGenerating}
            style={{
              width: '100%', padding: '16px', borderRadius: 12, border: 'none',
              background: isGenerating ? '#9ca3af' : '#1A3C6E',
              color: '#fff', fontSize: 15, fontWeight: 700,
              cursor: isGenerating ? 'not-allowed' : 'pointer', marginBottom: 12,
            }}
          >🔮 시놉시스 생성하기</button>
        ) : (
          <>
            <button
              onClick={() => navigate('/novel-studio')}
              style={{
                width: '100%', padding: '14px', borderRadius: 12,
                border: '2px solid #1A3C6E', background: '#fff', color: '#1A3C6E',
                fontSize: 14, fontWeight: 600, cursor: 'pointer', marginBottom: 10,
              }}
            >✏️ 서사 수정하기</button>

            <button
              onClick={handleGenerateSynopsisLegacy}
              disabled={isGenerating}
              style={{
                width: '100%', padding: '14px', borderRadius: 12,
                border: '1.5px solid #d1d5db', background: '#f9fafb', color: '#6B7280',
                fontSize: 13, fontWeight: 500,
                cursor: isGenerating ? 'not-allowed' : 'pointer', marginBottom: 10,
              }}
            >🔄 시놉시스 다시 생성</button>

            <button
              onClick={handleGenerateStoryLegacy}
              disabled={isGenerating}
              style={{
                width: '100%', padding: '16px', borderRadius: 12, border: 'none',
                background: isGenerating ? '#9ca3af' : '#10b981',
                color: '#fff', fontSize: 15, fontWeight: 700,
                cursor: isGenerating ? 'not-allowed' : 'pointer', marginBottom: 10,
              }}
            >📖 이야기 생성하기 (최종)</button>

            <button
              onClick={() => window.print()}
              style={{
                width: '100%', padding: '12px', borderRadius: 12,
                border: '1.5px solid #d1d5db', background: '#fff', color: '#6B7280',
                fontSize: 13, fontWeight: 500, cursor: 'pointer',
              }}
            >📄 PDF로 저장</button>
          </>
        )}
      </div>
    );
  }

  // ─────────────────────────────────────
  // RENDER — 기록 기반 모드 (구조 분석 + 3차 재생성)
  // ─────────────────────────────────────
  return (
    <div style={{
      maxWidth: 1100, margin: '0 auto', padding: '20px 16px',
      minHeight: 'calc(100vh - 56px - 80px)',
      backgroundColor: '#FAF9F6',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 22 }}>🔮</span>
          <h1 style={{ fontSize: 18, fontWeight: 700, color: '#1A3C6E', margin: 0 }}>
            HARU예언 — {synopsisRound}차 시놉시스
          </h1>
        </div>
        <button
          onClick={() => navigate('/record-prophecy')}
          style={{
            background: 'none', border: 'none', cursor: 'pointer',
            fontSize: 13, color: '#6B7280', padding: '6px 10px', borderRadius: 8,
          }}
        >← 설정으로</button>
      </div>

      <div style={{
        background: '#FFFBF0', border: '0.5px solid #F9CB42',
        borderRadius: 10, padding: '10px 12px', marginBottom: 16,
        fontSize: 12, color: '#633806', lineHeight: 1.7,
      }}>
        💡 좌측 표를 수정하면 우측 시놉시스에 즉시 반영됩니다.
        최대 3차까지 다시 생성할 수 있습니다. (현재 {synopsisRound}차)
      </div>

      <ProphecyDiagram analysis={{
        chars: analysis.chars,
        relationship: analysis.relationship,
        desire: analysis.desire,
        shackle: analysis.shackle,
        events: analysis.events,
        theme: analysis.theme,
      }} />

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
        gap: 16,
        marginTop: 16,
      }} className="haru-split">
        <div style={{ background: '#fff', borderRadius: 14, padding: 16, border: '0.5px solid #e5e7eb' }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: '#1A3C6E', marginTop: 0, marginBottom: 14 }}>
            📊 10항목 분석표 (수정 가능)
          </h3>
          {[
            { key: 'chars', label: '① 등장인물', icon: '👤' },
            { key: 'relationship', label: '② 인간관계', icon: '🤝' },
            { key: 'personality', label: '③ 인물 성격', icon: '🎭' },
            { key: 'desire', label: '④ 추구하는 것', icon: '🌱' },
            { key: 'shackle', label: '⑤ 극복할 것', icon: '⛓️' },
            { key: 'events', label: '⑥ 주요 사건', icon: '📌', textarea: true },
            { key: 'motive', label: '⑦ 사건 모티브', icon: '🎬' },
            { key: 'theme', label: '⑧ 주제·기획의도', icon: '🎯' },
            { key: 'oneLiner', label: '⑨ 한 줄 스토리', icon: '📝' },
            { key: 'threeLiner', label: '⑩ 세 줄 스토리', icon: '📃', textarea: true },
          ].map(({ key, label, icon, textarea }) => (
            <div key={key} style={{ marginBottom: 10 }}>
              <p style={{ fontSize: 11, color: '#6b7280', marginBottom: 4, marginTop: 0 }}>
                {icon} {label}
              </p>
              {textarea ? (
                <textarea
                  value={(analysis as any)[key]}
                  onChange={e => setAnalysis(prev => ({ ...prev, [key]: e.target.value }))}
                  rows={3}
                  style={{ width: '100%', border: '0.5px solid #e5e7eb', borderRadius: 8, padding: '8px 10px', fontSize: 16, color: '#374151', outline: 'none', resize: 'none', fontFamily: 'inherit', boxSizing: 'border-box' }}
                />
              ) : (
                <input
                  value={(analysis as any)[key]}
                  onChange={e => setAnalysis(prev => ({ ...prev, [key]: e.target.value }))}
                  style={{ width: '100%', border: '0.5px solid #e5e7eb', borderRadius: 8, padding: '8px 10px', fontSize: 16, color: '#374151', outline: 'none', boxSizing: 'border-box' }}
                />
              )}
            </div>
          ))}
        </div>

        <div style={{ background: '#fff', borderRadius: 14, padding: 20, border: '1.5px solid #C7D2FE' }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: '#1A3C6E', marginTop: 0, marginBottom: 14 }}>
            🔮 {synopsisRound}차 시놉시스 미리보기
          </h3>
          <pre style={{
            fontSize: 13, color: '#374151', lineHeight: 1.9,
            whiteSpace: 'pre-wrap', wordBreak: 'break-word',
            margin: 0, fontFamily: 'inherit', maxHeight: 600, overflowY: 'auto',
          }}>
            {renderAnalysisAsText(analysis)}
          </pre>

          {synopsis && (
            <div style={{ marginTop: 20, paddingTop: 14, borderTop: '0.5px dashed #d1d5db' }}>
              <p style={{ fontSize: 11, color: '#9ca3af', marginBottom: 6 }}>
                🤖 AI가 생성한 시놉시스 본문
              </p>
              <p style={{
                fontSize: 13, color: '#374151', lineHeight: 1.9,
                whiteSpace: 'pre-wrap', margin: 0,
              }}>{synopsis}</p>
            </div>
          )}
        </div>
      </div>

      <div style={{ marginTop: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
        {synopsisRound < 3 && (
          <button
            onClick={() => handleGenerateSynopsis(true)}
            disabled={isGenerating}
            style={{
              width: '100%', padding: '14px', borderRadius: 12,
              border: '1.5px solid #1A3C6E', background: '#fff', color: '#1A3C6E',
              fontSize: 14, fontWeight: 600,
              cursor: isGenerating ? 'not-allowed' : 'pointer',
            }}
          >
            🔄 {synopsisRound + 1}차 시놉시스 생성 {synopsisRound === 2 ? '(마지막!)' : ''}
          </button>
        )}

        {synopsisRound >= 3 && (
          <div style={{
            background: '#F0FDF4', border: '0.5px solid #86EFAC',
            borderRadius: 10, padding: '10px 12px',
            fontSize: 12, color: '#15803D', textAlign: 'center',
          }}>
            ✅ 3차 시놉시스까지 완료. 더는 재생성할 수 없습니다. 표는 자유롭게 수정 가능.
          </div>
        )}

        <button
          onClick={handleGenerateStory}
          disabled={isGenerating}
          style={{
            width: '100%', padding: '16px', borderRadius: 12, border: 'none',
            background: isGenerating ? '#9ca3af' : '#10b981',
            color: '#fff', fontSize: 15, fontWeight: 700,
            cursor: isGenerating ? 'not-allowed' : 'pointer',
          }}
        >📖 최종 확정 → 이야기 생성하기</button>

        <button
          onClick={() => window.print()}
          style={{
            width: '100%', padding: '12px', borderRadius: 12,
            border: '1.5px solid #d1d5db', background: '#fff', color: '#6B7280',
            fontSize: 13, fontWeight: 500, cursor: 'pointer',
          }}
        >📄 시놉시스 PDF로 저장</button>
      </div>

      <style>{`
        @media (max-width: 768px) {
          .haru-split {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </div>
  );
}
