import { openApp, pageText } from '../runner/driver.mjs';
import { checkIsolation } from './batch3-helpers.mjs';
export const meta = { id:'p23-voiding', format:'배뇨일지', persona:{name:'조영수',age:66,gender:'남',job:'은퇴 교사',device:'Chromium 모바일 390×844',plan:'무료',goal:'하루 배뇨량·주야간 합계를 검산하고 입력 실수와 재접속을 확인한다.'},identity:{uid:'qa-p23-cho-youngsoo',displayName:'조영수',email:'p23@example.invalid',plan:'free'},scenario:['홈·건강정보 동의·배뇨일지','250·150ml 주야간 기록·재접속','빈 값·소수·음수 입력 실수','양식·저장 경로·격리']};
export async function run(ctx){
 const {page}=ctx, uid=meta.identity.uid;
 const enter=async()=>{await openApp(page);await page.getByText('HARU건강관리',{exact:true}).click();await page.waitForTimeout(500);const consent=page.getByRole('button',{name:'건강정보 수집·이용에 동의합니다',exact:true});if(await consent.isVisible()){await consent.click();await page.waitForTimeout(500);}await page.getByText('배뇨일지',{exact:true}).click();await page.waitForTimeout(700);if(await consent.isVisible()){await consent.click();await page.waitForTimeout(500);}};
 const entries=async()=>JSON.parse((await ctx.records(uid))[0]?.voiding_entries||'[]');
 const save=async(value)=>{await page.getByPlaceholder('양 (ml)').fill(value);await page.getByRole('button',{name:'기록',exact:true}).click();await page.waitForTimeout(500);};
 await ctx.setDay('2026-10-03','14:00');
 await ctx.step('홈 → 건강관리 → 동의 → 배뇨일지',async()=>{await enter();ctx.check('배뇨일지 화면에 진입한다',new URL(page.url()).pathname==='/sayu-health/voiding',page.url(),'중대');ctx.check('첫 화면은 기록이 없다',(await ctx.records(uid)).length===0,'','중대');});
 await ctx.step('주간 250ml·야간 150ml 기록·검산',async()=>{await save('250');await ctx.setDay('2026-10-03','23:30');await enter();await save('150');const recs=await ctx.records(uid), e=await entries();ctx.check('같은 날 기록 한 문서에 항목 2건이 누적된다',recs.length===1&&e.length===2,JSON.stringify(e),'치명');ctx.check('시간·수량이 원값과 일치한다',e[0]?.time==='14:00'&&e[0]?.amountMl===250&&e[1]?.time==='23:30'&&e[1]?.amountMl===150,JSON.stringify(e),'중대');const txt=await pageText(page);ctx.check('총 400ml·주간 250ml·야간 150ml·야간비율 37.5%를 표시한다',/총 배뇨량\s*400/.test(txt)&&/주간 배뇨\s*250ml/.test(txt)&&/야간 배뇨\s*150ml/.test(txt)&&/야간뇨 비율\s*37\.5/.test(txt),txt.slice(-1500),'중대');ctx.check('records 경로·YYYY-MM-DD·배뇨일지 형식이 유지된다',recs[0]?.path.startsWith(`users/${uid}/records/`)&&recs[0]?.date==='2026-10-03'&&JSON.stringify(recs[0]?.formats)==='["배뇨일지"]',recs[0]?.path,'치명');});
 await ctx.step('재접속·양식 표시·빈 수량 허용',async()=>{await enter();ctx.check('재접속 후 두 항목이 유지된다',(await entries()).length===2,'','치명');await page.getByRole('button',{name:/양식 보기/}).click();ctx.check('양식에 수량과 합계가 표시된다',(await pageText(page)).includes('250')&&(await pageText(page)).includes('150'),'','중대');await page.getByRole('button',{name:/🚽 기록/}).click();await save('');ctx.check('안내대로 양을 모르는 빈 값은 0ml로 저장된다',(await entries()).at(-1)?.amountMl===0,'','중대');});
 await ctx.step('소수·음수 수량 실수 처리',async()=>{for(const v of ['250.5','-100']){const before=(await entries()).length;await page.getByPlaceholder('양 (ml)').fill(v);const shown=await page.getByPlaceholder('양 (ml)').inputValue();await page.getByRole('button',{name:'기록',exact:true}).click();await page.waitForTimeout(500);const e=await entries(), added=e.slice(before);const ok=ctx.check('잘못 입력한 수량을 다른 양수 정수로 바꾸어 저장하지 않는다',added.length===0||(v==='250.5'&&added[0]?.amountMl===250.5),`입력 ${v} → 표시 ${shown} → 저장 ${JSON.stringify(added)}`);if(!ok)ctx.finding({severity:'중대',title:'배뇨일지 소수·음수 입력에서 기호를 제거해 다른 수량을 저장한다',detail:`입력 ${v}가 화면에서 ${shown}로 변하고 amountMl=${added[0]?.amountMl}로 저장됐다. SayuHealthVoidingPage.tsx onChange의 replace(/[^0-9]/g, '')와 handleQuickRecord의 parseInt가 원인이다. 빈 수량 0 허용과는 별개다.`});}});
 await ctx.step('한국시간 자정 이후 기록일 확인',async()=>{await ctx.setDay('2026-10-04','02:00');await enter();await save('200');const recs=await ctx.records(uid);const mine=recs.find(r=>JSON.parse(r.voiding_entries||'[]').some(e=>e.time==='02:00'&&e.amountMl===200));const ok=ctx.check('한국시간 10월4일 새벽 기록은 10월4일에 저장된다',mine?.date==='2026-10-04',`KST=2026-10-04 02:00, 저장일=${mine?.date}`);if(!ok)ctx.finding({severity:'중대',title:'배뇨일지 새벽 기록이 한국 날짜보다 하루 전 날짜에 저장된다',detail:`한국시간 2026-10-04 02:00에 200ml를 기록하자 date=${mine?.date} 문서에 추가됐다. SayuHealthVoidingPage.tsx getTodayStr()의 new Date().toISOString().slice(0,10)은 UTC 날짜를 사용하고 시간 문자열은 getHours/getMinutes로 현지 시간을 사용한다. 한국시간 자정~08:59의 날짜와 시간이 어긋난다.`});});
 await ctx.step('격리 확인',()=>checkIsolation(ctx));
}
