import { openApp, pageText } from '../runner/driver.mjs';
import { checkIsolation } from './batch3-helpers.mjs';
export const meta={id:'p24-law',format:'하루LAW',persona:{name:'노경수',age:49,gender:'남',job:'식당 사장',device:'Chromium 모바일 390×844',plan:'무료',goal:'질문·분석·오류·저장 흐름을 모의 응답으로 확인한다.'},identity:{uid:'qa-p24-no-kyungsoo',displayName:'노경수',email:'p24@example.invalid',plan:'free'},scenario:['홈 하루LAW·안내·빈 입력','결과 없음·통신 오류·질문 보존','질문 분석 표시·날짜 검증·저장','기존 같은 날짜 기록 보존·재접속']};
export async function run(ctx){const {page}=ctx, uid=meta.identity.uid;await ctx.setDay('2026-10-03');
 await ctx.step('홈 → 하루LAW 안내·질문 입력',async()=>{await openApp(page);await page.getByText('하루LAW',{exact:true}).first().click();await page.getByRole('button',{name:'확인했습니다, 자문 받기 →',exact:true}).click();const q=page.getByRole('textbox',{name:'하루LAW 질문',exact:true});await q.waitFor();ctx.check('질문 입력창 높이는 235px 이상이다',(await q.boundingBox()).height>=235,'','중대');const before=(await ctx.qa()).calls.filter(c=>c.name==='lawSearch').length;await page.getByRole('button',{name:'법률자문',exact:true}).click();ctx.check('빈 질문은 서버 호출을 하지 않는다',(await ctx.qa()).calls.filter(c=>c.name==='lawSearch').length===before,'','중대');});
 for(const marker of ['[모의 결과 없음]','[모의 오류]'])await ctx.step(`${marker} 응답·입력 보존`,async()=>{const q=page.getByRole('textbox',{name:'하루LAW 질문',exact:true});await q.fill(marker+' 직원이 노동청에 신고했어요');await page.getByRole('button',{name:'법률자문',exact:true}).click();await page.waitForTimeout(700);ctx.check('실패 뒤 질문이 유지된다',(await q.inputValue()).includes(marker),'','중대');ctx.check('실패 안내와 재입력 화면을 표시한다',marker.includes('결과 없음')?(await pageText(page)).includes('관련 법령을 찾지 못했습니다'):(await pageText(page)).includes('다시'),(await pageText(page)).slice(-800),'중대');ctx.check('실패 응답은 기록을 만들지 않는다',(await ctx.records(uid)).length===0,'','치명');});
 const query='직원이 노동청에 신고했어요.\n급여 이체 내역과 근무표는 가지고 있습니다.';
 await ctx.step('모의 결과·원질문 표시·빈 저장 날짜 방지',async()=>{await page.getByRole('textbox',{name:'하루LAW 질문',exact:true}).fill(query);await page.getByRole('button',{name:'법률자문',exact:true}).click();await page.waitForTimeout(700);const txt=await pageText(page);ctx.check('모의 법령·모의 분석과 원질문을 표시한다',txt.includes('모의 법령')&&txt.includes('[모의 분석')&&txt.replace(/\s+/g,' ').includes(query.replace(/\s+/g,' ')),'','중대');await page.locator('#law-save-date').fill('');await page.getByRole('button',{name:'💾 사유-나의 기록에 저장',exact:true}).click();ctx.check('빈 저장 날짜는 안내하고 저장하지 않는다',(await ctx.records(uid)).length===0&&(await pageText(page)).includes('저장 날짜를 선택해 주세요'),'','중대');});
 await ctx.step('기존 날짜 기록과 함께 분석 저장',async()=>{await page.evaluate(async ({uid})=>{const sdk=await import('/sdk.ts');await sdk.setDoc(sdk.doc(sdk.db,'users',uid,'records','2026-10-02'),{date:'2026-10-02',formats:['메모'],content:'보존할 기존 기록',memo_title:'기존 메모',memo_content:'기존 본문'});},{uid});await page.locator('#law-save-date').fill('2026-10-02');await page.getByRole('button',{name:'💾 사유-나의 기록에 저장',exact:true}).click();await page.waitForTimeout(1000);const r=(await ctx.records(uid))[0];ctx.check('선택 날짜의 records 문서에 저장한다',r?.path===`users/${uid}/records/2026-10-02`&&r?.date==='2026-10-02',r?.path,'치명');ctx.check('하루LAW 원질문·모의 분석을 그대로 저장한다',r?.haruraw_query===query&&r?.haruraw_sayu?.startsWith('[모의 분석')&&r?.sourceAgent==='하루LAW','','치명');ctx.check('기존 형식·본문·메모 필드를 보존한다',r?.formats.includes('메모')&&r?.formats.includes('HARUraw')&&r?.content==='보존할 기존 기록'&&r?.memo_content==='기존 본문','','치명');ctx.check('저장 후 SAYU로 이동한다',new URL(page.url()).pathname==='/sayu',page.url(),'중대');await page.reload();await page.waitForTimeout(900);ctx.check('재접속 후 저장 원질문이 유지된다',(await ctx.records(uid))[0]?.haruraw_query===query,'','치명');});
 await ctx.step('격리 확인',()=>checkIsolation(ctx));}
