import { openApp,pageText } from '../runner/driver.mjs';
import { checkIsolation } from './batch3-helpers.mjs';
import { pause } from './batch6-helpers.mjs';
export const meta={id:'p27-lawsuit',format:'전자소송연습',persona:{name:'박성민',age:38,gender:'남',job:'직장인',device:'Chromium 모바일 390×844',plan:'무료',goal:'현재 지원되는 대여금 반환 사례로 절차 연습·모의 AI 초안·사건 저장을 확인한다.'},identity:{uid:'qa-p27-park-sungmin',displayName:'박성민',email:'p27@example.invalid',plan:'free'},scenario:['홈·초보 안내·법률정보 동의·인증 연습','동의 방지·사건·금액·당사자·청구 입력','모의 AI 초안·수동 입력·증거·검토·모의 제출','제출준비 사건 저장·재접속·격리']};
export async function run(ctx){const {page}=ctx,uid=meta.identity.uid;await ctx.setDay('2026-10-03');const next=async()=>{await page.getByRole('button',{name:'다음',exact:true}).click();await pause(page);};
 await ctx.step('홈 → 초보 안내 → 연습 진입',async()=>{await openApp(page);await page.getByText('전자소송연습비서',{exact:true}).first().click();await pause(page);await page.getByRole('button',{name:'화면 설명 시작하기',exact:true}).click();await pause(page);for(let i=0;i<10;i++){const home=page.getByRole('button',{name:'전자소송연습비서 홈으로',exact:true});if(await home.isVisible()){await home.click();break;}await next();}await pause(page);await page.getByRole('button',{name:/새로 소송을 준비하고 있어요/}).click();await pause(page);const consent=page.getByRole('button',{name:/정보 수집·이용에 동의합니다/});if(await consent.isVisible()){await consent.click();await pause(page);}ctx.check('연습이 실제 법원 제출이 아님을 표시한다',(await pageText(page)).includes('실제 법원에 제출되지 않습니다'),'','중대');});
 await ctx.step('인증 연습·서류·유형·동의 방지',async()=>{await page.getByRole('button',{name:'로그인',exact:true}).click();await pause(page);ctx.check('인증서 없이 진행 버튼은 비활성이다',await page.getByRole('button',{name:'전자소송 작성 연습 계속하기',exact:true}).isDisabled(),'','중대');await page.getByRole('button',{name:'인증서 로그인 과정 연습',exact:true}).click();await page.getByRole('button',{name:'전자소송 작성 연습 계속하기',exact:true}).click();await pause(page);const legalConsent=page.getByRole('button',{name:/법률정보 수집.*이용에 동의합니다/});if(await legalConsent.isVisible()){await legalConsent.click();await pause(page);}await next();ctx.check('대여금 반환 유형이 보인다',(await pageText(page)).includes('대여금 반환'),'','중대');await next();ctx.check('연습 동의 전 다음은 비활성이다',await page.getByRole('button',{name:'다음',exact:true}).isDisabled(),'','중대');await page.getByRole('checkbox').check();await next();});
 const reason='2026년 9월 1일 480000원을 빌려주었다.\n9월 30일 반환 약속이 지났지만 받지 못했다.';
 await ctx.step('기본 정보·당사자·청구 입력',async()=>{await page.locator('input[placeholder^="예:"]').first().fill('빌려준 돈 연습');await page.getByPlaceholder('예: 480000원').fill('480000원');await next();await page.getByPlaceholder('예: 홍길동').fill('박성민');await page.getByPlaceholder('예: 1990.01.01').fill('1988.01.01');await page.getByPlaceholder('예: 김철수').fill('이민호');await next();await page.locator('textarea').fill('480000원의 반환을 구하는 연습 문장');await next();});
 await ctx.step('모의 AI 초안·직접 사실 입력·증거',async()=>{await page.getByRole('button',{name:/AI 초안 작성/}).click();await pause(page);ctx.check('모의 초안과 검토 안내를 표시한다',(await page.locator('textarea').inputValue()).includes('[모의 청구원인'),'','중대');await page.locator('textarea').fill(reason);await next();await page.getByRole('button',{name:/증거.*추가|추가.*연습/}).click();await next();ctx.check('검토표에 금액·당사자·직접 입력 사실이 보인다',(await pageText(page)).includes('박성민')&&(await pageText(page)).includes('이민호')&&(await pageText(page)).includes('480,000'),'','중대');await next();await page.getByRole('button',{name:'소장 제출하기(연습)',exact:true}).click();await pause(page);ctx.check('모의 사건번호를 표시한다',/2026가소\d+/.test(await pageText(page)),'','중대');ctx.check('실제 기록은 아직 저장되지 않았다',(await ctx.db()).filter(([p])=>p.includes('/legalCases/')).length===0,'','중대');});
 await ctx.step('사건으로 저장·재접속',async()=>{await page.getByRole('button',{name:'이 내용으로 사건 만들기',exact:true}).click();await pause(page);const cases=(await ctx.db()).filter(([p])=>new RegExp(`^users/${uid}/legalCases/[^/]+$`).test(p));ctx.check('본인 legalCases에 사건 한 건 저장한다',cases.length===1,'','치명');const r=cases[0]?.[1];ctx.check('제출준비 상태와 연습 기록으로 저장한다',r?.status==='제출준비'&&r?.caseNumber==='연습 기록'&&r?.submittedAt==='','','치명');ctx.check('금액·당사자·사실·청구취지를 보존한다',r?.claimAmount===480000&&r?.practiceDraft?.plaintiffName==='박성민'&&r?.practiceDraft?.defendantName==='이민호'&&r?.practiceDraft?.claimReason===reason,'','치명');ctx.check('실제 제출 체크리스트는 미확인 상태다',Object.values(r?.checklistSubmit||{}).length>0&&Object.values(r.checklistSubmit).every(v=>v===false),'','중대');await page.reload();await pause(page);ctx.check('재접속 사건 제목이 표시된다',(await pageText(page)).includes('빌려준 돈 연습'),'','중대');ctx.check('일상 records 문서를 만들지 않는다',(await ctx.records(uid)).length===0,'','중대');});
 await ctx.step('격리 확인',()=>checkIsolation(ctx));}
