import { openApp,pageText } from '../runner/driver.mjs';
import { checkIsolation } from './batch3-helpers.mjs';
import { seedLocal,pause } from './batch6-helpers.mjs';
export const meta={id:'p28-english',format:'영어일기',persona:{name:'정은희',age:45,gender:'여',job:'주부',device:'Chromium 모바일 390×844',plan:'무료',goal:'한글 직접 작성과 기존 일기 학습에서 입력 한도·오류·저장·번역 캐시 흐름을 확인한다.'},identity:{uid:'qa-p28-jung-eunhee',displayName:'정은희',email:'p28@example.invalid',plan:'free'},scenario:['홈 영어일기·빈 입력·1000자 제한','번역 모의 오류·입력 유지·오류 안내','정상 직접작성 저장·날짜·SAYU·재접속','기존 일기 번역·캐시·같은 길이 수정 fixture·격리']};
export async function run(ctx){const {page}=ctx,uid=meta.identity.uid;await ctx.setDay('2026-10-04','02:00');
 const enter=async()=>{await openApp(page);await page.getByText('영어일기',{exact:true}).first().click();await pause(page);};
 const translate=async()=>{await page.getByRole('button',{name:'🌐 영어로 번역하여 학습하기',exact:true}).click();await pause(page);};
 await ctx.step('홈 → 영어일기·직접 작성·한도',async()=>{await enter();await page.getByRole('button',{name:/직접 작성하기/}).click();ctx.check('빈 본문에서는 번역 버튼이 비활성이다',await page.getByRole('button',{name:'🌐 영어로 번역하여 학습하기',exact:true}).isDisabled(),'','중대');const input=page.getByPlaceholder('오늘 있었던 일이나 생각을 한글로 써보세요. (최대 1000자)');await input.fill('가'.repeat(1000));ctx.check('1000자 본문이 유지된다',(await input.inputValue()).length===1000,'','중대');await input.fill('가'.repeat(1001));ctx.check('1001자 입력 시 이전 1000자 본문을 보존한다',(await input.inputValue()).length===1000,'','중대');});
 await ctx.step('모의 번역 실패·입력 보존·오류 안내',async()=>{const input=page.getByPlaceholder('오늘 있었던 일이나 생각을 한글로 써보세요. (최대 1000자)');await input.fill('[모의 오류] 오늘 공원에 갔다.');await translate();ctx.check('실패 후 입력은 유지된다',(await input.inputValue())==='[모의 오류] 오늘 공원에 갔다.','','중대');ctx.check('실패 후 기록을 저장하지 않는다',(await ctx.records(uid)).length===0,'','치명');const txt=await pageText(page),toast=await ctx.toasts();const ok=ctx.check('번역 실패 시 사용자에게 오류 안내를 표시한다',/실패|오류|다시 시도/.test(txt+' '+toast.join(' ')),JSON.stringify(toast));if(!ok)ctx.finding({severity:'경미',title:'영어일기 번역 실패가 콘솔에만 기록되고 화면에는 오류 안내가 없다',detail:'translateToEnglish가 functions/unavailable을 반환하자 입력은 유지되고 번역 버튼만 복원됐다. 토스트·화면 오류 안내는 없었다. DiaryLearnPage handleDirectTranslate의 catch는 console.error만 실행한다.'});});
 const original='오늘 가족과 공원에 갔다. 😊\n즐거웠다.';
 await ctx.step('직접작성 모의 번역·새벽 날짜·원문 저장',async()=>{await page.getByPlaceholder('오늘 있었던 일이나 생각을 한글로 써보세요. (최대 1000자)').fill(original);await translate();const r=(await ctx.records(uid))[0];ctx.check('직접작성영어일기 형식으로 한 건 저장한다',JSON.stringify(r?.formats)==='["직접작성영어일기"]'&&r?.sourceAgent==='영어일기','','치명');ctx.check('원문 이모지·줄바꿈과 모의 번역을 저장한다',r?.english_diary_korean===original&&r?.english_diary_english==='Mock translation for isolated UI testing.','','치명');ctx.check('한국시간 새벽에도 날짜를 10월4일로 저장한다',r?.date==='2026-10-04'&&r?.path.startsWith(`users/${uid}/records/2026-10-04_english_diary_`),r?.path,'중대');await page.getByRole('button',{name:'나의 기록에서 보기',exact:true}).click();await pause(page);ctx.check('저장 뒤 SAYU로 이동한다',new URL(page.url()).pathname==='/sayu',page.url(),'중대');await page.reload();await pause(page);ctx.check('재접속 뒤 직접 작성 원문이 유지된다',(await ctx.records(uid))[0]?.english_diary_korean===original,'','치명');});
 const id='2026-10-02_fixture_diary',old='오늘 산책을 했다.',changed='오늘 독서를 했다.';const openDiary=async()=>{await enter();await page.getByRole('button',{name:/일기에서 가져오기/}).click();await pause(page);await page.getByText('학습할 일기',{exact:true}).click();await pause(page);};
 await ctx.step('기존 일기 번역·동일 본문 캐시 재사용',async()=>{await seedLocal(page,[[`users/${uid}/records/${id}`,{date:'2026-10-02',formats:['일기'],diary_title:'학습할 일기',diary_content:old}]]);await openDiary();await translate();let calls=(await ctx.qa()).calls.filter(c=>c.name==='translateToEnglish').length;let r=(await ctx.records(uid)).find(r=>r.path.endsWith(id));ctx.check('기존 일기 번역을 캐시로 저장한다',r?._english_sentences?.[0]==='Mock walk sentence.'&&r?._english_source_length===old.length,'','중대');await openDiary();await translate();ctx.check('본문이 같으면 추가 번역 호출 없이 캐시를 재사용한다',(await ctx.qa()).calls.filter(c=>c.name==='translateToEnglish').length===calls,'','중대');});
 await ctx.step('같은 글자 수 본문 변경 fixture·캐시 무효화',async()=>{ctx.check('변경 fixture 두 본문은 길이가 같다',old.length===changed.length,'','중대');await seedLocal(page,[[`users/${uid}/records/${id}`,{diary_content:changed}]]);await openDiary();ctx.check('상세 원문은 수정된 본문이다',(await pageText(page)).includes(changed),'','중대');const before=(await ctx.qa()).calls.filter(c=>c.name==='translateToEnglish').length;await translate();const after=(await ctx.qa()).calls.filter(c=>c.name==='translateToEnglish').length;const ok=ctx.check('내용이 바뀌면 같은 길이라도 번역 캐시를 갱신한다',after===before+1,`길이 ${old.length} 동일, 호출 ${before} → ${after}, 이전 번역 표시=${(await pageText(page)).includes('Mock walk sentence.')}`);if(!ok)ctx.finding({severity:'중대',title:'영어일기는 본문을 같은 글자 수로 바꾸면 이전 번역 캐시를 계속 사용한다',detail:`기존 '${old}'를 번역한 상태에서 기존 사용자의 수정 후 상태를 fixture로 '${changed}'로 구성했다. 상세 원문은 변경됐지만 번역 호출은 ${before}→${after}, 학습 화면은 이전 Mock walk sentence.를 표시했다. DiaryLearnPage handleTranslate 캐시 조건은 문장 존재·본문 길이만 비교한다. 실제 SAYU 편집 화면의 수정 동작은 이번 fixture 검증에 포함하지 않았다.`});});
 await ctx.step('격리 확인',()=>checkIsolation(ctx));}
