import { openApp,pageText } from '../runner/driver.mjs';
import { checkIsolation } from './batch3-helpers.mjs';
import { pause } from './batch6-helpers.mjs';
export const meta={id:'p29-sns',format:'SNS 갈무리',persona:{name:'오유진',age:41,gender:'여',job:'쇼핑몰 자영업자',device:'Chromium 모바일 390×844',plan:'무료',goal:'ZIP 선택·모의 수집·검색 저장·SNS 휴지통·복원·재접속을 확인한다.'},identity:{uid:'qa-p29-oh-yujin',displayName:'오유진',email:'p29@example.invalid',plan:'free'},scenario:['홈·비ZIP 거부','ZIP 모의 오류·재시도·타임라인','검색·검색결과 저장','휴지통·복원·재접속·격리']};
export async function run(ctx){const {page}=ctx,uid=meta.identity.uid;await ctx.setDay('2026-10-04','02:00');
 const docs=async kind=>(await ctx.db()).filter(([p])=>p.startsWith(`users/${uid}/${kind}/`));
 const upload=async name=>{await page.locator('input[type=file]').setInputFiles({name,mimeType:name.endsWith('.zip')?'application/zip':'text/plain',buffer:name.endsWith('.zip')?Buffer.from('504b05060000000000000000000000000000000000000000','hex'):Buffer.from('Synthetic text')});await pause(page);};
 await ctx.step('홈 → SNS·비ZIP 입력 거부',async()=>{await openApp(page);await page.getByText('SNS 갈무리',{exact:true}).first().click();await pause(page);await upload('not-a-zip.txt');ctx.check('비ZIP 파일은 업로드 없이 안내한다',(await ctx.qa()).uploads.length===0&&(await ctx.toasts()).some(t=>t.includes('ZIP 파일만')),'','중대');ctx.check('초기 타임라인 저장 기록이 없다',(await docs('snsRecords')).length===0,'','치명');});
 await ctx.step('ZIP 모의 실패·재시도·수집 완료',async()=>{await page.evaluate(()=>window.__qaBatch7Failure='analyzeFacebookZip');await upload('mock-failed.zip');ctx.check('ZIP 분석 오류를 화면에 안내한다',(await ctx.toasts()).some(t=>t.includes('격리 ZIP 분석 실패')),'','중대');ctx.check('오류 응답에서는 SNS 기록이 생기지 않는다',(await docs('snsRecords')).length===0,'','치명');await page.evaluate(()=>window.__qaBatch7Failure='');await upload('mock-posts.zip');ctx.check('모의 SNS 세 건이 본인 snsRecords에 수집된다',(await docs('snsRecords')).length===3,'','치명');const txt=await pageText(page);ctx.check('한글·이모지·줄바꿈 게시물이 표시된다',txt.includes('소중한 추억')&&txt.includes('🎂')&&txt.includes('쇼핑몰 신상품'),'','중대');ctx.check('ZIP 업로드는 본인 snsUploads 경로다',(await ctx.qa()).uploads.every(x=>x.path.startsWith(`users/${uid}/snsUploads/`)),'','치명');});
 const search=page.getByPlaceholder(/키워드로 검색/);
 await ctx.step('검색 적용·검색결과 저장·빈 상태',async()=>{await search.fill('가족');await page.getByRole('button',{name:/검색하기/}).click();await pause(page);const txt=await pageText(page);ctx.check('가족 검색은 무관한 쇼핑몰 게시물을 제외한다',txt.includes('소중한 추억')&&!txt.includes('쇼핑몰 신상품'),'','중대');await page.getByRole('button',{name:/검색결과 저장/}).click();await pause(page);const data=(await docs('snsSearchHistory'))[0]?.[1];ctx.check('검색결과 두 건과 검색어를 저장한다',data?.results?.length===2&&data?.keyword==='가족','','치명');ctx.check('검색결과 저장 date는 한국시간 오늘이다',data?.date==='2026-10-04',data?.date,'중대');await search.fill('없는키워드');await page.getByRole('button',{name:/검색하기/}).click();await pause(page);ctx.check('빈 검색에는 저장 버튼이 없다',await page.getByRole('button',{name:/검색결과 저장/}).count()===0,'','중대');await search.fill('');await page.getByRole('button',{name:/검색하기/}).click();await pause(page);});
 await ctx.step('SNS 휴지통 이동·복원·재접속',async()=>{const before=await docs('snsRecords');const confirm=async d=>{ctx.events.dialogs.push({type:d.type(),message:d.message()});if(d.type()==='confirm')await d.accept().catch(()=>{});else await d.dismiss().catch(()=>{});};page.removeAllListeners('dialog');page.on('dialog',confirm);await page.getByRole('button',{name:/삭제/}).first().click();await pause(page);let rows=await docs('snsRecords');const removed=rows.find(([,d])=>d.isDeleted);ctx.check('삭제는 한 건만 휴지통 표시하고 원문을 보존한다',rows.length===3&&rows.filter(([,d])=>d.isDeleted).length===1&&removed?.[1].text===before.find(([p])=>p===removed?.[0])?.[1].text,'','치명');await page.getByRole('button',{name:/SNS 휴지통 1/}).click();await pause(page);ctx.check('휴지통에서는 검색결과 저장 버튼이 없다',await page.getByRole('button',{name:/검색결과 저장/}).count()===0,'','중대');await page.getByRole('button',{name:/복원/}).first().click();await pause(page);ctx.check('복원 뒤 삭제 표시와 deletedAt을 제거한다',(await docs('snsRecords')).every(([,d])=>!d.isDeleted&&!d.deletedAt),'','치명');await page.reload();await pause(page);ctx.check('재접속 후 세 게시물과 복원이 유지된다',(await pageText(page)).includes('보관중 3')&&(await docs('snsRecords')).length===3,'','치명');});
 await ctx.step('격리 확인',()=>checkIsolation(ctx));}
