import {openApp,pageText} from '../runner/driver.mjs';
import {testImage} from '../runner/assets.mjs';
import {checkIsolation} from './batch3-helpers.mjs';
import {pause} from './batch6-helpers.mjs';
export const meta={id:'p30-plant',format:'하루식물탐정',persona:{name:'박미란',age:57,gender:'여',job:'베란다 식물 30종 보호자',device:'Chromium 모바일 390×844',plan:'무료',goal:'합성 사진·분석 오류·모의 판독·관찰 저장·재접속을 확인한다.'},identity:{uid:'qa-p30-park-miran',displayName:'박미란',email:'p30@example.invalid',plan:'free'},scenario:['홈·빈 사진·사진 추가','모의 분석 오류·재시도','관찰과 판독 저장·재접속·격리']};
export async function run(ctx){const{page}=ctx,uid=meta.identity.uid;await ctx.setDay('2026-10-04','02:00');
 await ctx.step('홈 → 식물탐정·빈 사진·추가',async()=>{await openApp(page);await page.getByText('하루식물탐정',{exact:true}).first().click();await pause(page);ctx.check('사진이 없으면 분석 버튼이 비활성이다',await page.getByRole('button',{name:'식물 탐정 시작',exact:true}).isDisabled(),'','중대');await page.locator('input[type=file]').first().setInputFiles([testImage('모의-호접란-1.png'),testImage('모의-호접란-2.png')]);await page.waitForTimeout(1800);ctx.check('사진 두 장이 추가되고 분석할 수 있다',await page.getByRole('button',{name:'사진 제거',exact:true}).count()===2&&!await page.getByRole('button',{name:'식물 탐정 시작',exact:true}).isDisabled(),'','중대');});
 await ctx.step('모의 식물 분석 실패·입력 유지·재시도',async()=>{await page.evaluate(()=>window.__qaBatch7Failure='detectPlantAdvanced');await page.getByRole('button',{name:'식물 탐정 시작',exact:true}).click();await pause(page);ctx.check('모의 실패 후 오류 안내와 사진을 보존한다',(await ctx.toasts()).length>0&&await page.getByRole('button',{name:'사진 제거',exact:true}).count()===2,'','중대');ctx.check('분석 실패는 기록을 저장하지 않는다',(await ctx.records(uid)).length===0,'','치명');await page.evaluate(()=>window.__qaBatch7Failure='');await page.getByRole('button',{name:'식물 탐정 시작',exact:true}).click();await pause(page);ctx.check('재시도 성공 시 모의 판독 결과를 표시한다',(await pageText(page)).includes('모의 판독'),'','중대');const call=(await ctx.qa()).calls.filter(c=>c.name==='detectPlantAdvanced').at(-1);ctx.check('분석 요청에 사진 두 장을 전달한다',call?.input?.images?.length===2&&call.input.images.every(i=>i.imageBase64&&i.mimeType),'','중대');});
 await ctx.step('관찰·메모·촬영장소·오늘 기록 저장',async()=>{await page.getByPlaceholder(/오늘 무엇을 관찰했나요/).first().fill('잎 두 장이 새로 나왔다. 🌱\n물을 주었다.');await page.getByPlaceholder('자유 메모\n예: 비 온 뒤 성장 속도가 빨라졌어요').fill('베란다 창가 관찰 메모');await page.getByPlaceholder('촬영장소 (예: 지리산 노고단)').fill('우리집 베란다');await page.getByRole('button',{name:/오늘 기록 저장/}).click();await pause(page);const r=(await ctx.records(uid))[0];ctx.check('판독·관찰이 오늘 records 문서에 함께 저장된다',r?.path===`users/${uid}/records/2026-10-04`&&r?.date==='2026-10-04'&&r?.plantDetective?.length===1&&r?.plantObservation?.length===1,JSON.stringify(r).slice(0,250),'치명');ctx.check('관찰 원문·이모지·줄바꿈·메모를 보존한다',r?.plantObservation?.[0]?.observation==='잎 두 장이 새로 나왔다. 🌱\n물을 주었다.'&&r.plantObservation[0].memo==='베란다 창가 관찰 메모','','치명');ctx.check('사진 두 장은 본인 format_photos에 저장한다',r?.plantDetective?.[0]?.imageUrls?.length===2&&(await ctx.qa()).uploads.every(u=>u.path.startsWith(`users/${uid}/format_photos/`)),'','치명');ctx.check('저장 후 중복 저장 버튼을 비활성화한다',await page.getByRole('button',{name:/오늘 기록에 저장됨/}).isDisabled(),'','중대');await page.reload();await pause(page);ctx.check('재접속 후 판독·관찰 기록이 보존된다',(await ctx.records(uid))[0]?.plantObservation?.length===1,'','치명');});
 await ctx.step('격리 확인',()=>checkIsolation(ctx));}
