import {openApp,pageText} from '../runner/driver.mjs';
import {checkIsolation} from './batch3-helpers.mjs';
import {pause} from './batch6-helpers.mjs';
export const meta={id:'p31-onbid',format:'온비드 부동산',persona:{name:'김성훈',age:50,gender:'남',job:'직장인',device:'Chromium 모바일 390×844',plan:'무료',goal:'조회 조건·페이지 이동·결과 없음·실패 안내·외부 링크 의도를 확인한다.'},identity:{uid:'qa-p31-kim-sunghoon',displayName:'김성훈',email:'p31@example.invalid',plan:'free'},scenario:['홈·조회 조건·모의 결과','다음 페이지·온비드 링크 의도','빈 결과·오류·재시도·격리']};
export async function run(ctx){const{page}=ctx;await ctx.setDay('2026-10-04');await page.context().addInitScript(()=>{window.__qaOpened=[];window.open=url=>{window.__qaOpened.push(String(url));return null;};});const search=async()=>{await page.getByRole('button',{name:/검색하기/}).click();await pause(page);};
 await ctx.step('홈 → 온비드·조건 조회',async()=>{await openApp(page);await page.getByText('온비드 부동산',{exact:true}).first().click();await pause(page);await page.locator('select').nth(1).selectOption('서울특별시');await page.getByPlaceholder('예) 송파구').fill(' 송파구 ');await page.getByPlaceholder('예) 아파트, 대지').fill(' 아파트 ');await page.getByPlaceholder('예) 100000000').fill('100000000');await page.getByPlaceholder('예) 500000000').fill('500000000');await search();const call=(await ctx.qa()).calls.find(c=>c.name==='getOnbidRealEstateList');ctx.check('본인 조건을 첫 페이지 조회 payload로 보낸다',call?.input?.pageNo===1&&call?.input?.lctnSggnm==='송파구'&&call?.input?.onbidCltrNm==='아파트'&&call?.input?.lowstBidPrcStart==='100000000',JSON.stringify(call?.input),'중대');const txt=await pageText(page);ctx.check('모의 가격·물건·입찰일을 표시한다',txt.includes('격리 공매 물건 1')&&txt.includes('2억원')&&txt.includes('2026.10.09'),'','중대');});
 await ctx.step('페이지 이동·외부 링크 의도',async()=>{ctx.check('첫 페이지 이전 버튼이 비활성이다',await page.getByRole('button',{name:'← 이전',exact:true}).isDisabled(),'','경미');await page.getByRole('button',{name:'다음 →',exact:true}).click();await pause(page);const calls=(await ctx.qa()).calls.filter(c=>c.name==='getOnbidRealEstateList');ctx.check('다음 조회는 같은 조건과 pageNo 2를 보낸다',calls.at(-1)?.input?.pageNo===2&&calls.at(-1)?.input?.onbidCltrNm==='아파트','','중대');ctx.check('두 번째 결과와 마지막 페이지 버튼을 표시한다',(await pageText(page)).includes('격리 공매 물건 2')&&await page.getByRole('button',{name:'다음 →',exact:true}).isDisabled(),'','중대');await page.getByRole('button',{name:/격리 공매 물건 2/}).click();await pause(page);ctx.check('외부 이동 의도는 온비드 공식 홈페이지다',(await page.evaluate(()=>window.__qaOpened)).at(-1)==='https://www.onbid.co.kr/','','중대');});
 await ctx.step('빈 결과·조회 오류·재시도',async()=>{await page.getByPlaceholder('예) 아파트, 대지').fill('결과없음');await search();ctx.check('0건 조회 후 이전 물건을 제거하고 빈 상태를 안내한다',(await pageText(page)).includes('검색 결과가 없습니다')&&!(await pageText(page)).includes('격리 공매 물건 2'),'','중대');await page.evaluate(()=>window.__qaBatch7Failure='getOnbidRealEstateList');await page.getByPlaceholder('예) 아파트, 대지').fill('아파트');await search();ctx.check('조회 실패는 오류 안내와 재시도 가능한 버튼을 제공한다',(await ctx.toasts()).some(t=>t.includes('격리 온비드 조회 실패'))&&!await page.getByRole('button',{name:/검색하기/}).isDisabled(),'','중대');await page.evaluate(()=>window.__qaBatch7Failure='');await search();ctx.check('재시도는 첫 페이지부터 결과를 복원한다',(await pageText(page)).includes('격리 공매 물건 1'),'','중대');ctx.check('조회 비서는 records 문서를 쓰지 않는다',(await ctx.records(meta.identity.uid)).length===0,'','치명');});
 await ctx.step('격리 확인',()=>checkIsolation(ctx));}
